### ISSUE TITLE
how  and where do we set any env variable like I want to export WATCHMEN_WEB_NO_AUTH='true' how do I do it

### ISSUE THREAD

**Issue by pineshmenat** [iloire/watchmen#110]

**Comment by lorranpego** [comment]
That is not related to the project, but to OS and Node.JS itself.

http://www.koreatimes.co.kr/www/world/2019/03/685_265128.html

**Comment by lorranpego** [comment]
It is not related to the project, but to OS and Node.Js itself.

https://stackoverflow.com/questions/22312671/setting-environment-variables-for-node-to-retrieve

**Comment by fergatron** [comment]
I was able to get it by updating the `./config/web.js` file with: 

```
process.env['WATCHMEN_WEB_NO_AUTH'] = 'true';
```

**Comment by lorranpego** [comment]
@pineshmenat @fergatron 
Since we didn't have many interaction in this repository, I created a copy of it and made some modifications.

https://github.com/lorranpego/watchmen

On my copy, you can set the configuration files at `config/.env` and it will be loaded when the process start.

**Comment by pineshmenat** [comment]
Thank you all for your response, closing it now
