### ISSUE TITLE
SMTP not working at all?

### ISSUE THREAD

**Issue by sraupach** [iloire/WatchMen#18]
If i configure a Host to be monitored over SMTP it says it is "down" but i am able to connect via telnet (port25)

my configuration is correct..i even see WatchMen connect at my SMTP-Server.

**Comment by iloire** [comment]
@sraupach I haven't used the SMTP service myself that much. Please feel free to send a PR with some tests and I will merge it, or if you could just provide the tests that cover the failing case, I may fix it myself.

**Comment by iloire** [comment]
SMTP is not supported out of the box in watchmen 3. Anyone is free to create its own implementation through a custom ping service and share it.

Examples of ping services:
https://www.npmjs.com/package/watchmen-ping-http-contains
https://www.npmjs.com/package/watchmen-ping-http-head
