### ISSUE TITLE
Enhance http ping service

### ISSUE THREAD

**Issue by tcoupin** [iloire/WatchMen#25]
Ideas :
- http request headers
- basic authentification

**Comment by tcoupin** [comment]
After looking the code, headers already seem to be supported. Can you confirm?

**Comment by iloire** [comment]
It doesn't check for headers at the moment. It checks for status code and response content

**Comment by renderful** [comment]
Another nice idea in this area might be to notify and log when certain content is on the page, such as error messages.

**Comment by iloire** [comment]
It will be soon possible to plug your own ping services, and one that does that should be quite simple to implement.

**Comment by iloire** [comment]
Since watchmen 3, please refer to

https://www.npmjs.com/package/watchmen-ping-http-head
https://www.npmjs.com/package/watchmen-ping-http-contains
