### ISSUE TITLE
Any plans or possibility to use basic smtp to send emails?

### ISSUE THREAD

**Issue by VarunBatraIT** [iloire/watchmen#47]

**Comment by iloire** [comment]
No plans (from my side), but many possibilities! :)
You can create your own plugin to use SMTP as transport in a similar way to https://github.com/iloire/watchmen-plugin-aws-ses

**Comment by emilyhorsman** [comment]
I've made a plugin to send SMTP email with nodemailer! Emails templates are created with Handlebars and come with some defaults but can be overriden. Pull requests welcome.

https://www.npmjs.com/package/watchmen-plugin-nodemailer

**Comment by VarunBatraIT** [comment]
@emilyhorsman Thank you.

**Comment by iloire** [comment]
Thanks @emilyhorsman! I updated the README to include a link to the plugin and added you as a contributor.
