### ISSUE TITLE
Is there any way to develop without gulp-building?

### ISSUE THREAD

**Issue by zarzen** [iloire/watchmen#49]
I find that I need to build the javascript files after I modified them. And then add a script resource location "app.js" ,in the 'index.html' file. like this:
```
  <script src="<%=baseUrl%>build/vendor.js"></script>
  <script src="<%=baseUrl%>build/app.js"></script>
```
So it can finally works. I wonder know, if there are some ways to allow me to develop without building.
Seems include all raw js file is not a good idea.

**Comment by iloire** [comment]
You can just run ``gulp watch`` and it will take care of building the project for you in the background when you do changes. Or are you missing something in particular?

**Comment by zarzen** [comment]
But in this way, gulp still will compile the js file. it's hard for debugging. 
So i am using it in a wrong way? sorry i am not a newbie in js-world.

**Comment by iloire** [comment]
The ``gulp watch`` should be calling the ``js-dev`` gulp task that does not minify the JS bundle
