### ISSUE TITLE
is it possible to ping ips thats not running any services?

### ISSUE THREAD

**Issue by pavs** [iloire/watchmen#54]

**Comment by zarzen** [comment]
I think it's possible. because nodejs can invoke the local command. so you can write an ping-service, to call linux command or windows command `ping`, and handle the output message.

**Comment by iloire** [comment]
You are supposed to easily create a watchmen ping module that uses something like https://github.com/stephenwvickers/node-net-ping. If you do, feel free to ping me so I can list it in the public contributions!
