### ISSUE TITLE
Is it possible to work without oauth ?

### ISSUE THREAD

**Issue by vladyslav2** [iloire/watchmen#61]
Hello. 
watchmen looks like a greate solutions.

but i think you have a lack of documentation.

Is it possible to work without google oauth ?
Is it possible to login as an admin without using oauth ?
is it possible to add domain without web interface at all ?

thanks !

**Comment by brownman** [comment]
u can use this patch:
```bash
wget https://patch-diff.githubusercontent.com/raw/iloire/watchmen/pull/58.patch
mv 58.patch ../
git am ../58.patch
```

**Comment by gtrias** [comment]
Nice work! Thank you
Since this patch adds the functionality as a configurable property. Couldn't be applied as a pull request in the project? That way we could have the latest changes without to worry about apply patches.

**Comment by gtrias** [comment]
Oh I've just saw that there's already a pull request. I guess the project is not maintainled anymore?

**Comment by iloire** [comment]
Yes, it is still maintained. The PR has been merged, sorry for the delay.

**Comment by gtrias** [comment]
Thank you a lot!
