### ISSUE TITLE
Make services async

### ISSUE THREAD

**Issue by dscape** [iloire/WatchMen#7]
The way you coded this you need to specify resources in a file. It would be useful to do http calls to get a dynamic list of servers to ping.

**Comment by ericelliott** [comment]
I see this issue was opened 3 years ago... is this actively maintained?

**Comment by iloire** [comment]
@ericelliott Yes, it is. I guess nobody has issued a PR for this yet... If you do, I will happily review it and merge it.

**Comment by ericelliott** [comment]
:+1:

**Comment by iloire** [comment]
Thanks for raising this issue. This has been Implemented in b8b5bb59c54e5355e6de1e4f499dc60c4e5aeb1e
